'use strict';
const $=id=>document.getElementById(id), audio=$('audio');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clock=s=>Math.floor((s||0)/60)+':'+String(Math.floor((s||0)%60)).padStart(2,'0');
let data=window.GLIA_PLAYLIST||{title:'Kept songs',tracks:[]}, selected=null, playing=null, queue=[];
function song(id){return data.tracks.find(t=>t.id===id);}
function filtered(){let list=data.tracks.filter(t=>[t.title,t.style,t.lyrics].join(' ').toLowerCase().includes($('search').value.toLowerCase()));return list.sort((a,b)=>$('sort').value==='newest'?String(b.created).localeCompare(String(a.created)):$('sort').value==='title'?a.title.localeCompare(b.title):b.rating-a.rating||a.title.localeCompare(b.title));}
function render(){const list=filtered();$('page-title').textContent=data.title;document.title=data.title+' · glia.ca';$('collection-note').textContent=data.tracks.length+' songs · '+clock(data.tracks.reduce((s,t)=>s+Number(t.duration||0),0))+' of music';$('song-list').innerHTML=list.map(t=>`<article class="song ${selected===t.id?'selected':''} ${playing?.id===t.id?'active':''}"><button data-play="${esc(t.id)}" aria-label="Play ${esc(t.title)}">${playing?.id===t.id&&!audio.paused?'Ⅱ':'▶'}</button><div class="cover" aria-hidden="true">${esc(t.title.slice(0,1))}</div><button class="title" data-details="${esc(t.id)}" aria-label="Show details for ${esc(t.title)}"><strong>${esc(t.title)}</strong><small>${esc(String(t.created||'').slice(0,10))}</small></button><span class="rating">${'★'.repeat(t.rating)}<small>${clock(t.duration)}</small></span></article>`).join('');$('empty').hidden=!!list.length;$('play-all').disabled=!list.length;}
function detail(t){if(!t)return;selected=t.id;$('song-details').innerHTML=`<h2>${esc(t.title)}</h2><p class="meta">${t.rating}/5 stars · ${clock(t.duration)}</p><button class="play-detail" data-play="${esc(t.id)}">▶ Play this song</button><h3>Lyrics</h3><pre>${esc(t.lyrics||'Instrumental · no lyrics supplied')}</pre>${t.style?`<details><summary>About the sound</summary><p>${esc(t.style)}</p></details>`:''}`;render();}
async function play(id){const t=song(id);if(!t)return;if(playing?.id===id){try{if(audio.paused)await audio.play();else audio.pause();}catch{$('playing-note').textContent='Audio could not be loaded. Try Play again.';}return;}queue=filtered().map(t=>t.id);playing=t;audio.src=t.audio;detail(t);$('playing-title').textContent=t.title;try{await audio.play();}catch{$('playing-note').textContent='Press Play to begin listening.';}render();}
function shift(delta){const i=queue.indexOf(playing?.id),next=queue[i+delta];if(next)play(next);}
document.addEventListener('click',e=>{const p=e.target.closest('[data-play]'),d=e.target.closest('[data-details]');if(p)play(p.dataset.play);if(d)detail(song(d.dataset.details));});
$('play-all').onclick=()=>{if(filtered()[0])play(filtered()[0].id);};$('toggle').onclick=()=>playing?play(playing.id):$('play-all').click();$('previous').onclick=()=>shift(-1);$('next').onclick=()=>shift(1);$('reveal').onclick=()=>detail(playing);
$('search').oninput=render;$('sort').onchange=render;audio.volume=.8;$('volume').oninput=e=>audio.volume=Number(e.target.value);$('seek').oninput=e=>{if(Number.isFinite(audio.duration))audio.currentTime=audio.duration*Number(e.target.value)/100;};
audio.addEventListener('timeupdate',()=>{$('elapsed').textContent=clock(audio.currentTime);$('duration').textContent=clock(audio.duration);$('seek').value=audio.duration?audio.currentTime/audio.duration*100:0;});
for(const event of ['play','pause'])audio.addEventListener(event,()=>{$('toggle').textContent=audio.paused?'▶':'Ⅱ';$('toggle').setAttribute('aria-label',audio.paused?'Play':'Pause');$('playing-note').textContent=audio.paused?'Paused':'Playing';render();});audio.addEventListener('ended',()=>shift(1));audio.addEventListener('error',()=>{$('playing-note').textContent='Audio unavailable. Check that the audio folder was uploaded.';});
async function refresh(){try{const response=await fetch('playlist.json?v='+Date.now());if(!response.ok)return;const next=await response.json();if(next.updated===data.updated)return;data=next;render();if(song(selected))detail(song(selected));}catch{}}
render();if(data.tracks[0])detail(data.tracks[0]);if(location.protocol==='http:'||location.protocol==='https:')setInterval(refresh,30000);
